version: "3"

services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      # Working
      - ../:/workspaces/ld06_test:cached
      # GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev:rw
    tty: true
    command: sleep inf
    working_dir: /workspaces/ld06_test
    privileged: true
    ipc: host
